/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'blog-posts': BlogPost;
    endorsements: Endorsement;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    endorsements: EndorsementsSelect<false> | EndorsementsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  /**
   * Shown in the admin UI and can be used publicly (e.g. author byline). Must be unique.
   */
  username: string;
  /**
   * Optional profile image (stored in the Media collection).
   */
  avatar?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Blog posts support drafts, published dates, and Lexical rich text content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  /**
   * Used in the URL. Auto-generated from the title, but you can edit it.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Set automatically when a post is first published (you can override).
   */
  publishedAt?: string | null;
  /**
   * Short summary used on the blog listing page and in metadata.
   */
  excerpt?: string | null;
  /**
   * Main post content (Lexical rich text). Use headings, links, and lists.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (string | null) | Media;
  /**
   * Optional credit line for stock/third-party images (e.g. Unsplash). If any field is filled, we’ll render a subtle “Photo by … on …” caption on the post.
   */
  imageAttribution?: {
    platformName?: string | null;
    /**
     * Link to the platform (or the platform’s credit URL if required).
     */
    platformUrl?: string | null;
    artistName?: string | null;
    /**
     * Link to the artist/photographer profile page.
     */
    artistUrl?: string | null;
    /**
     * Link to the original image page (often required for attribution).
     */
    imageUrl?: string | null;
  };
  /**
   * Optional tags for filtering and discovery (e.g. Next.js, Payload, TypeScript).
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  author?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Short endorsements from clients and colleagues. All new submissions start as pending and must be approved before they appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "endorsements".
 */
export interface Endorsement {
  id: string;
  /**
   * Only endorsements marked as Approved will be displayed publicly on the site.
   */
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Timestamp for when this endorsement was approved. Set automatically on first approval, but you can override it.
   */
  approvedAt?: string | null;
  /**
   * Full name of the person giving the endorsement. They can choose whether this is shown publicly.
   */
  endorserName: string;
  /**
   * Optional contact email used only for verification or clarification. This is never displayed on the public site.
   */
  endorserEmail?: string | null;
  /**
   * How this person has worked with you. This helps future employers and clients understand the context.
   */
  relationshipType: 'client' | 'colleague' | 'manager' | 'directReport' | 'other';
  /**
   * Their role or title at the time you worked together (e.g. Delivery Manager, Product Owner, Lead Developer).
   */
  roleOrTitle?: string | null;
  /**
   * Company name or project context (e.g. Thames Water transformation programme).
   */
  companyOrProject?: string | null;
  /**
   * Optional LinkedIn profile link to lend extra credibility to the endorsement.
   */
  linkedinUrl?: string | null;
  /**
   * 2–4 sentences describing what it was like to work with you, focused on impact and reliability. You may lightly edit for clarity and spelling before publishing.
   */
  endorsementText: string;
  /**
   * The submitter can choose which details are shown publicly alongside their endorsement.
   */
  displayPreferences?: {
    showNamePublicly?: boolean | null;
    showCompanyOrProjectPublicly?: boolean | null;
    showLinkedinUrlPublicly?: boolean | null;
  };
  /**
   * The submitter must explicitly consent before their endorsement can be published on your site.
   */
  consentToPublish: boolean;
  /**
   * Technical metadata captured at submission time (IP, user agent, etc.). Not shown publicly.
   */
  submissionMeta?: {
    ipAddress?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'endorsements';
        value: string | Endorsement;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  username?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  imageAttribution?:
    | T
    | {
        platformName?: T;
        platformUrl?: T;
        artistName?: T;
        artistUrl?: T;
        imageUrl?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "endorsements_select".
 */
export interface EndorsementsSelect<T extends boolean = true> {
  status?: T;
  approvedAt?: T;
  endorserName?: T;
  endorserEmail?: T;
  relationshipType?: T;
  roleOrTitle?: T;
  companyOrProject?: T;
  linkedinUrl?: T;
  endorsementText?: T;
  displayPreferences?:
    | T
    | {
        showNamePublicly?: T;
        showCompanyOrProjectPublicly?: T;
        showLinkedinUrlPublicly?: T;
      };
  consentToPublish?: T;
  submissionMeta?:
    | T
    | {
        ipAddress?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}