/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    tags: Tag;
    'tag-colors': TagColor;
    experiences: Experience;
    endorsements: Endorsement;
    'blog-posts': BlogPost;
    'changelog-entries': ChangelogEntry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'tag-colors': TagColorsSelect<false> | TagColorsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    endorsements: EndorsementsSelect<false> | EndorsementsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'changelog-entries': ChangelogEntriesSelect<false> | ChangelogEntriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    roadmap: Roadmap;
  };
  globalsSelect: {
    roadmap: RoadmapSelect<false> | RoadmapSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  /**
   * Shown in the admin UI and can be used publicly (e.g. author byline). Must be unique.
   */
  username: string;
  /**
   * Optional profile image (stored in the Media collection).
   */
  avatar?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for accessibility and SEO
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Categories can be scoped to specific collections (e.g. Blog posts now, other content types later).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  /**
   * Human-friendly label shown on the site (e.g. Engineering).
   */
  name: string;
  /**
   * Used for filtering and URLs. Auto-generated from the name, but you can edit it.
   */
  slug: string;
  /**
   * Controls where this category can be selected. Each collection filters the category picker to only show relevant categories.
   */
  scopes: ('blog-posts' | 'changelog-entries')[];
  /**
   * Optional summary shown in admin and can be used for SEO/UX later.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable tags for blog posts, experiences, and other content. Tags can be scoped to specific collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  /**
   * Tag label shown on the site (e.g. TypeScript, React, Leadership). Keep it consistent and canonical.
   */
  name: string;
  /**
   * Used for filtering and URLs. Auto-generated from the name, but you can edit it.
   */
  slug: string;
  /**
   * Controls where this tag can be selected. Each collection filters the tag picker to only show relevant tags. Select all that apply.
   */
  scopes: ('blog-posts' | 'experiences' | 'changelog-entries')[];
  /**
   * Optional context about when to use this tag (helpful for content authors).
   */
  description?: string | null;
  /**
   * Optional color scheme for this tag. The selected color's Tailwind classes will be applied when rendering this tag in the UI.
   */
  color?: (string | null) | TagColor;
  updatedAt: string;
  createdAt: string;
}
/**
 * Define color schemes for tags. Each color includes all required Tailwind classes for consistent styling across light and dark modes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tag-colors".
 */
export interface TagColor {
  id: string;
  /**
   * Descriptive name for this color scheme (e.g. Violet, Emerald, Sky).
   */
  name: string;
  /**
   * Used programmatically to reference this color. Auto-generated from the name.
   */
  slug: string;
  /**
   * Complete Tailwind class string for this color (e.g. "bg-violet-500/10 text-violet-700 ring-1 ring-violet-500/25 hover:bg-violet-500/15 dark:text-violet-300"). Include light mode, dark mode, and hover states.
   */
  tailwindClasses: string;
  /**
   * Tailwind background color for preview (e.g. "bg-violet-500"). Used for visual reference in the admin UI.
   */
  previewSwatch?: string | null;
  /**
   * Optional usage guidance (e.g. 'Use for technology/framework tags', 'Use for soft skills').
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * CV experience entries. Dates are stored as real dates; the UI will format them later (e.g. yyyy-MMM, with “Present” for current roles).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: string;
  /**
   * Company/organisation name (e.g. “Cadent Gas”).
   */
  company: string;
  /**
   * Role title (e.g. “Lead Developer”).
   */
  title: string;
  /**
   * Start date for the role. The UI will decide how to format it (e.g. yyyy-MMM).
   */
  fromDate: string;
  /**
   * Enable this for your current role. When enabled, the UI can render the end date as “Present”.
   */
  isCurrentRole?: boolean | null;
  /**
   * End date for the role. Leave empty when “Current role” is enabled.
   */
  toDate?: string | null;
  /**
   * Controls ordering on the resume. Decide the sort logic in the UI (e.g. descending by fromDate, then by sortOrder).
   */
  sortOrder?: number | null;
  /**
   * Structured content for the experience entry. Mirrors your current “mixed” model (paragraphs + headed bullet sections).
   */
  content: {
    /**
     * Experiences currently use `type: mixed` (paragraph blocks plus headed bullet sections).
     */
    type: 'mixed';
    /**
     * Content blocks rendered in order. Use a Paragraph for narrative text, and a Section for headed bullet lists.
     */
    sections: {
      /**
       * Select the block type for this row.
       */
      type: 'paragraph' | 'section';
      /**
       * Paragraph text. Keep it readable and impact-focused.
       */
      text?: string | null;
      /**
       * Section heading (e.g. “Key Tasks and responsibilities”).
       */
      heading?: string | null;
      /**
       * Bullet points for the section. Keep each item short and specific.
       */
      items?:
        | {
            /**
             * A single bullet point.
             */
            item: string;
            id?: string | null;
          }[]
        | null;
      id?: string | null;
    }[];
  };
  /**
   * Technologies/skills used in this role. Select from the centralized tags collection.
   */
  tags?: (string | Tag)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Short endorsements from clients and colleagues. All new submissions start as pending and must be approved before they appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "endorsements".
 */
export interface Endorsement {
  id: string;
  /**
   * Only endorsements marked as Approved will be displayed publicly on the site.
   */
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Timestamp for when this endorsement was approved. Set automatically on first approval, but you can override it.
   */
  approvedAt?: string | null;
  /**
   * Full name of the person giving the endorsement. They can choose whether this is shown publicly.
   */
  endorserName: string;
  /**
   * Optional contact email used only for verification or clarification. This is never displayed on the public site.
   */
  endorserEmail?: string | null;
  /**
   * How this person has worked with you. This helps future employers and clients understand the context.
   */
  relationshipType: 'client' | 'colleague' | 'manager' | 'directReport' | 'other';
  /**
   * Their role or title at the time you worked together (e.g. Delivery Manager, Product Owner, Lead Developer).
   */
  roleOrTitle?: string | null;
  /**
   * Company name or project context (e.g. Thames Water transformation programme).
   */
  companyOrProject?: string | null;
  /**
   * Optional LinkedIn profile link to lend extra credibility to the endorsement.
   */
  linkedinUrl?: string | null;
  /**
   * 2–4 sentences describing what it was like to work with you, focused on impact and reliability. You may lightly edit for clarity and spelling before publishing.
   */
  endorsementText: string;
  /**
   * The submitter can choose which details are shown publicly alongside their endorsement.
   */
  displayPreferences?: {
    showNamePublicly?: boolean | null;
    showCompanyOrProjectPublicly?: boolean | null;
    showLinkedinUrlPublicly?: boolean | null;
  };
  /**
   * The submitter must explicitly consent before their endorsement can be published on your site.
   */
  consentToPublish: boolean;
  /**
   * Technical metadata captured at submission time (IP, user agent, etc.). Not shown publicly.
   */
  submissionMeta?: {
    ipAddress?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog posts support drafts, published dates, and Lexical rich text content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  /**
   * Used in the URL. Auto-generated from the title, but you can edit it.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Set automatically when a post is first published (you can override).
   */
  publishedAt?: string | null;
  /**
   * Short summary used on the blog listing page and in metadata.
   */
  excerpt?: string | null;
  /**
   * Optional category used for filtering (e.g. Engineering, Deep dives).
   */
  category?: (string | null) | Category;
  /**
   * Main post content (Lexical rich text). Use headings, links, and lists.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (string | null) | Media;
  /**
   * Optional credit line for stock/third-party images (e.g. Unsplash). If any field is filled, we’ll render a subtle “Photo by … on …” caption on the post.
   */
  imageAttribution?: {
    platformName?: string | null;
    /**
     * Link to the platform (or the platform’s credit URL if required).
     */
    platformUrl?: string | null;
    artistName?: string | null;
    /**
     * Link to the artist/photographer profile page.
     */
    artistUrl?: string | null;
    /**
     * Link to the original image page (often required for attribution).
     */
    imageUrl?: string | null;
  };
  /**
   * Optional tags for filtering and discovery (e.g. Next.js, Payload, TypeScript). Select from the centralized tags collection.
   */
  tags?: (string | Tag)[] | null;
  author?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Changelog entries are short, structured release notes. Use the blog for deep dives and longer write-ups.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "changelog-entries".
 */
export interface ChangelogEntry {
  id: string;
  /**
   * Human-friendly summary (e.g. “Projects section now CMS-backed”).
   */
  title: string;
  /**
   * Used in the URL. Auto-generated from the title, but you can edit it.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Date the change shipped (not the date you clicked Publish). You can backdate this.
   */
  publishedAt: string;
  /**
   * Optional version label (e.g. v1.3.0). Useful if you start tagging releases.
   */
  version?: string | null;
  /**
   * 1–2 sentence overview shown on the changelog listing page.
   */
  summary: string;
  /**
   * The structured change list. Keep each item short and user-facing.
   */
  changes: {
    type: 'added' | 'changed' | 'fixed' | 'removed' | 'security';
    text: string;
    /**
     * Optional link for extra context. Internal links should be used for your own content (e.g. a deep-dive blog post).
     */
    linkKind: 'none' | 'external' | 'internal';
    /**
     * Full URL (e.g. https://example.com).
     */
    externalUrl?: string | null;
    /**
     * Choose which internal content to link to. Add more options as new content types ship.
     */
    internalCollection?: 'blog-posts' | null;
    /**
     * Select the blog post to link to.
     */
    internalBlogPost?: (string | null) | BlogPost;
    id?: string | null;
  }[];
  /**
   * Optional deep dive blog post that explains this change in more detail.
   */
  relatedPost?: (string | null) | BlogPost;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'tag-colors';
        value: string | TagColor;
      } | null)
    | ({
        relationTo: 'experiences';
        value: string | Experience;
      } | null)
    | ({
        relationTo: 'endorsements';
        value: string | Endorsement;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'changelog-entries';
        value: string | ChangelogEntry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  username?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  scopes?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  scopes?: T;
  description?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tag-colors_select".
 */
export interface TagColorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tailwindClasses?: T;
  previewSwatch?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  company?: T;
  title?: T;
  fromDate?: T;
  isCurrentRole?: T;
  toDate?: T;
  sortOrder?: T;
  content?:
    | T
    | {
        type?: T;
        sections?:
          | T
          | {
              type?: T;
              text?: T;
              heading?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "endorsements_select".
 */
export interface EndorsementsSelect<T extends boolean = true> {
  status?: T;
  approvedAt?: T;
  endorserName?: T;
  endorserEmail?: T;
  relationshipType?: T;
  roleOrTitle?: T;
  companyOrProject?: T;
  linkedinUrl?: T;
  endorsementText?: T;
  displayPreferences?:
    | T
    | {
        showNamePublicly?: T;
        showCompanyOrProjectPublicly?: T;
        showLinkedinUrlPublicly?: T;
      };
  consentToPublish?: T;
  submissionMeta?:
    | T
    | {
        ipAddress?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  excerpt?: T;
  category?: T;
  content?: T;
  featuredImage?: T;
  imageAttribution?:
    | T
    | {
        platformName?: T;
        platformUrl?: T;
        artistName?: T;
        artistUrl?: T;
        imageUrl?: T;
      };
  tags?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "changelog-entries_select".
 */
export interface ChangelogEntriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  version?: T;
  summary?: T;
  changes?:
    | T
    | {
        type?: T;
        text?: T;
        linkKind?: T;
        externalUrl?: T;
        internalCollection?: T;
        internalBlogPost?: T;
        id?: T;
      };
  relatedPost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Content shown on the public /roadmap page. Update the copy and bullets here without changing code.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap".
 */
export interface Roadmap {
  id: string;
  /**
   * Small uppercase label above the heading.
   */
  kicker: string;
  heading: string;
  lead: string;
  note?: string | null;
  /**
   * Optional buttons shown under the intro copy (e.g. anchor links to sections on the homepage).
   */
  ctaLinks?:
    | {
        label: string;
        /**
         * Internal links (e.g. /#projects) are recommended.
         */
        href: string;
        variant: 'outline' | 'ghost';
        id?: string | null;
      }[]
    | null;
  /**
   * Items you are actively working on right now.
   */
  now: {
    /**
     * Toggle to hide this column from the public roadmap page.
     */
    isVisible?: boolean | null;
    title: string;
    description: string;
    bullets: {
      text: string;
      id?: string | null;
    }[];
  };
  /**
   * Items you plan to tackle once the current work lands.
   */
  next: {
    /**
     * Toggle to hide this column from the public roadmap page.
     */
    isVisible?: boolean | null;
    title: string;
    description: string;
    bullets: {
      text: string;
      id?: string | null;
    }[];
  };
  /**
   * Longer-term improvements and operational polish.
   */
  later: {
    /**
     * Toggle to hide this column from the public roadmap page.
     */
    isVisible?: boolean | null;
    title: string;
    description: string;
    bullets: {
      text: string;
      id?: string | null;
    }[];
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap_select".
 */
export interface RoadmapSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  lead?: T;
  note?: T;
  ctaLinks?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  now?:
    | T
    | {
        isVisible?: T;
        title?: T;
        description?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  next?:
    | T
    | {
        isVisible?: T;
        title?: T;
        description?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  later?:
    | T
    | {
        isVisible?: T;
        title?: T;
        description?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}